/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  CollectionURI,
  CollectionURIInterface,
} from "../../interface/CollectionURI";

const _abi = [
  {
    inputs: [],
    name: "contractURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class CollectionURI__factory {
  static readonly abi = _abi;
  static createInterface(): CollectionURIInterface {
    return new utils.Interface(_abi) as CollectionURIInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CollectionURI {
    return new Contract(address, _abi, signerOrProvider) as CollectionURI;
  }
}
