/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export type DeploymentConfigStruct = {
  contractType: PromiseOrValue<BytesLike>;
  chainType: PromiseOrValue<BigNumberish>;
  salt: PromiseOrValue<BytesLike>;
  byteCode: PromiseOrValue<BytesLike>;
  initCode: PromiseOrValue<BytesLike>;
};

export type DeploymentConfigStructOutput = [
  string,
  number,
  string,
  string,
  string
] & {
  contractType: string;
  chainType: number;
  salt: string;
  byteCode: string;
  initCode: string;
};

export type VerificationStruct = {
  r: PromiseOrValue<BytesLike>;
  s: PromiseOrValue<BytesLike>;
  v: PromiseOrValue<BigNumberish>;
};

export type VerificationStructOutput = [string, string, number] & {
  r: string;
  s: string;
  v: number;
};

export type BridgeSettingsStruct = {
  value: PromiseOrValue<BigNumberish>;
  gasLimit: PromiseOrValue<BigNumberish>;
  gasPrice: PromiseOrValue<BigNumberish>;
  toChain: PromiseOrValue<BigNumberish>;
};

export type BridgeSettingsStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  number
] & {
  value: BigNumber;
  gasLimit: BigNumber;
  gasPrice: BigNumber;
  toChain: number;
};

export interface HolographFactoryInterface extends utils.Interface {
  functions: {
    "admin()": FunctionFragment;
    "adminCall(address,bytes)": FunctionFragment;
    "bridgeIn(uint32,bytes)": FunctionFragment;
    "bridgeOut(uint32,address,bytes)": FunctionFragment;
    "deployHolographableContract((bytes32,uint32,bytes32,bytes,bytes),(bytes32,bytes32,uint8),address)": FunctionFragment;
    "deployHolographableContractMultiChain((bytes32,uint32,bytes32,bytes,bytes),(bytes32,bytes32,uint8),address,bool,(uint256,uint256,uint256,uint32)[])": FunctionFragment;
    "getAdmin()": FunctionFragment;
    "getHolograph()": FunctionFragment;
    "getRegistry()": FunctionFragment;
    "init(bytes)": FunctionFragment;
    "setAdmin(address)": FunctionFragment;
    "setHolograph(address)": FunctionFragment;
    "setRegistry(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "admin"
      | "adminCall"
      | "bridgeIn"
      | "bridgeOut"
      | "deployHolographableContract"
      | "deployHolographableContractMultiChain"
      | "getAdmin"
      | "getHolograph"
      | "getRegistry"
      | "init"
      | "setAdmin"
      | "setHolograph"
      | "setRegistry"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "adminCall",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "bridgeIn",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "bridgeOut",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deployHolographableContract",
    values: [DeploymentConfigStruct, VerificationStruct, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "deployHolographableContractMultiChain",
    values: [
      DeploymentConfigStruct,
      VerificationStruct,
      PromiseOrValue<string>,
      PromiseOrValue<boolean>,
      BridgeSettingsStruct[]
    ]
  ): string;
  encodeFunctionData(functionFragment: "getAdmin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getHolograph",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "init",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "setAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setHolograph",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setRegistry",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "adminCall", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bridgeIn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bridgeOut", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deployHolographableContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployHolographableContractMultiChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getHolograph",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "init", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setHolograph",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRegistry",
    data: BytesLike
  ): Result;

  events: {
    "BridgeableContractDeployed(address,bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BridgeableContractDeployed"): EventFragment;
}

export interface BridgeableContractDeployedEventObject {
  contractAddress: string;
  hash: string;
}
export type BridgeableContractDeployedEvent = TypedEvent<
  [string, string],
  BridgeableContractDeployedEventObject
>;

export type BridgeableContractDeployedEventFilter =
  TypedEventFilter<BridgeableContractDeployedEvent>;

export interface HolographFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: HolographFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    admin(overrides?: CallOverrides): Promise<[string]>;

    adminCall(
      target: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    bridgeIn(
      arg0: PromiseOrValue<BigNumberish>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    bridgeOut(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string, string] & { selector: string; data: string }>;

    deployHolographableContract(
      config: DeploymentConfigStruct,
      signature: VerificationStruct,
      signer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    deployHolographableContractMultiChain(
      config: DeploymentConfigStruct,
      signature: VerificationStruct,
      signer: PromiseOrValue<string>,
      deployOnCurrentChain: PromiseOrValue<boolean>,
      bridgeSettings: BridgeSettingsStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getAdmin(
      overrides?: CallOverrides
    ): Promise<[string] & { adminAddress: string }>;

    getHolograph(
      overrides?: CallOverrides
    ): Promise<[string] & { holograph: string }>;

    getRegistry(
      overrides?: CallOverrides
    ): Promise<[string] & { registry: string }>;

    init(
      initPayload: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setAdmin(
      adminAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setHolograph(
      holograph: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setRegistry(
      registry: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  admin(overrides?: CallOverrides): Promise<string>;

  adminCall(
    target: PromiseOrValue<string>,
    data: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  bridgeIn(
    arg0: PromiseOrValue<BigNumberish>,
    payload: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  bridgeOut(
    arg0: PromiseOrValue<BigNumberish>,
    arg1: PromiseOrValue<string>,
    payload: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<[string, string] & { selector: string; data: string }>;

  deployHolographableContract(
    config: DeploymentConfigStruct,
    signature: VerificationStruct,
    signer: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  deployHolographableContractMultiChain(
    config: DeploymentConfigStruct,
    signature: VerificationStruct,
    signer: PromiseOrValue<string>,
    deployOnCurrentChain: PromiseOrValue<boolean>,
    bridgeSettings: BridgeSettingsStruct[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getAdmin(overrides?: CallOverrides): Promise<string>;

  getHolograph(overrides?: CallOverrides): Promise<string>;

  getRegistry(overrides?: CallOverrides): Promise<string>;

  init(
    initPayload: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setAdmin(
    adminAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setHolograph(
    holograph: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setRegistry(
    registry: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    admin(overrides?: CallOverrides): Promise<string>;

    adminCall(
      target: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    bridgeIn(
      arg0: PromiseOrValue<BigNumberish>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    bridgeOut(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string, string] & { selector: string; data: string }>;

    deployHolographableContract(
      config: DeploymentConfigStruct,
      signature: VerificationStruct,
      signer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    deployHolographableContractMultiChain(
      config: DeploymentConfigStruct,
      signature: VerificationStruct,
      signer: PromiseOrValue<string>,
      deployOnCurrentChain: PromiseOrValue<boolean>,
      bridgeSettings: BridgeSettingsStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    getAdmin(overrides?: CallOverrides): Promise<string>;

    getHolograph(overrides?: CallOverrides): Promise<string>;

    getRegistry(overrides?: CallOverrides): Promise<string>;

    init(
      initPayload: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    setAdmin(
      adminAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setHolograph(
      holograph: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setRegistry(
      registry: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "BridgeableContractDeployed(address,bytes32)"(
      contractAddress?: PromiseOrValue<string> | null,
      hash?: PromiseOrValue<BytesLike> | null
    ): BridgeableContractDeployedEventFilter;
    BridgeableContractDeployed(
      contractAddress?: PromiseOrValue<string> | null,
      hash?: PromiseOrValue<BytesLike> | null
    ): BridgeableContractDeployedEventFilter;
  };

  estimateGas: {
    admin(overrides?: CallOverrides): Promise<BigNumber>;

    adminCall(
      target: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    bridgeIn(
      arg0: PromiseOrValue<BigNumberish>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    bridgeOut(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deployHolographableContract(
      config: DeploymentConfigStruct,
      signature: VerificationStruct,
      signer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    deployHolographableContractMultiChain(
      config: DeploymentConfigStruct,
      signature: VerificationStruct,
      signer: PromiseOrValue<string>,
      deployOnCurrentChain: PromiseOrValue<boolean>,
      bridgeSettings: BridgeSettingsStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getAdmin(overrides?: CallOverrides): Promise<BigNumber>;

    getHolograph(overrides?: CallOverrides): Promise<BigNumber>;

    getRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    init(
      initPayload: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setAdmin(
      adminAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setHolograph(
      holograph: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setRegistry(
      registry: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    admin(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    adminCall(
      target: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    bridgeIn(
      arg0: PromiseOrValue<BigNumberish>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    bridgeOut(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deployHolographableContract(
      config: DeploymentConfigStruct,
      signature: VerificationStruct,
      signer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    deployHolographableContractMultiChain(
      config: DeploymentConfigStruct,
      signature: VerificationStruct,
      signer: PromiseOrValue<string>,
      deployOnCurrentChain: PromiseOrValue<boolean>,
      bridgeSettings: BridgeSettingsStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getAdmin(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getHolograph(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getRegistry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    init(
      initPayload: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setAdmin(
      adminAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setHolograph(
      holograph: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setRegistry(
      registry: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
