/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HolographERC20 } from "./HolographERC20";
export type { HolographERC721 } from "./HolographERC721";
export type { HolographGeneric } from "./HolographGeneric";
export type { HolographRoyalties } from "./HolographRoyalties";
export type { Holographer } from "./Holographer";
